# Generated by Django 4.1.3 on 2023-01-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='eamil',
            new_name='email',
        ),
    ]
