# Generated by Django 4.1.3 on 2023-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='DevSearch/devsearch/static/images/user-default.png', null=True, upload_to='DevSearch/devsearch/static/images/'),
        ),
    ]
